name = "Gamerpack"
author = "Fatboychummy"
version = "0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d102be9118a53f9abfa9f4e84e4ee97e4cc35d95514782f3ac347a5b72b7ebe1"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
