name = "Gamerpack"
author = "The Gamers"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59e1deecfcd6a81328dc5c84ae5e5bcbd22f9fb6caa186b655554bd5bcb51a05"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
