name = "Gamerpack"
author = "The Gamers"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ced26fe0a7bdb548bec92123b292c19d12f57ab6bfba5823ae67bfedda00d22"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
